package ru.ls.qa.school.addressbook.tests;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import com.codeborne.selenide.Configuration;
import com.codeborne.selenide.WebDriverRunner;
import static com.codeborne.selenide.Selectors.*;
import static com.codeborne.selenide.Selenide.*;
import static org.junit.jupiter.api.Assertions.*;
import org.openqa.selenium.Dimension;
import ru.ls.qa.school.addressbook.model.ContactCreationData;
import ru.ls.qa.school.addressbook.model.GroupData;
import ru.ls.qa.school.addressbook.tests.TestBase;

import java.util.*;
public class ContactDelitionTests extends TestBase {

  @BeforeEach
  public void precondition1() {
    page.groupPage()
            .goToGroupPage();
    if(! app.getGroupHelper().isThereAGroup()){
      app.getGroupHelper().createGroup(new GroupData(
              "test1",
              null,
              null));
    }
  }
  @BeforeEach
  public void precondition2() {
    page.mainPage()
            .initContactCreation();
    if(! app.getContactHelper().isThereAContact()){
      app.getContactHelper().createContact(new ContactCreationData(
              "Alex",
              "Zaytsev",
              "Sergeevich",
              "Zayats",
              "АУУ"));
    }
  }

  @Test
  void testContactDelition() {
    page.mainPage()
            .editContact()
            .deleteContact();
  }
}
