package ru.ls.qa.school.addressbook.tests.groups;// Generated by Selenium IDE

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.model.GroupData;
import ru.ls.qa.school.addressbook.tests.TestBase;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class GroupCreationTests extends TestBase {
    private static int before;

    @BeforeAll
    static void setUp() {
        page.groupListPage
                .goToGroupPage();
        before = app.getGroupHelper()
                    .getGroupCount();
    }

    @Test
    public void testGroupCreation() {

        page.groupListPage
                .goToGroupPage()
                .initGroupCreation()
                .fillGroupForm(new GroupData(
                        "test1",
                        null,
                        null))
                .submitGroupForm()
                .goToGroupPage();
        int after = app.getGroupHelper()
                       .getGroupCount();
        assertEquals(before + 1, after);
    }

    /** Пример для сверки списков моделей
     ArrayList<GroupData> before = new ArrayList<>();
     ArrayList<GroupData> result = new ArrayList<>();
     before.add(new GroupData("1", "2", "3"));

     assertThat(result)
     .usingRecursiveComparison()
     .ignoringCollectionOrder()
     .ignoringFields("header", "footer")
     .isEqualTo(before);
     **/
}
