package ru.ls.qa.school.addressbook.tests.groups;// Generated by Selenium IDE

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.model.GroupData;
import ru.ls.qa.school.addressbook.tests.TestBase;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class GroupDelitionTests extends TestBase {

    private static int before;

    @BeforeAll
    static void setUp() {
        page.groupListPage
                .goToGroupPage();
        before = app.getGroupHelper()
                    .getGroupCount();
    }

    @BeforeEach
    public void precondition() {
        page.groupPage()
            .goToGroupPage();
        if (!app.getGroupHelper()
                .isThereAGroup()) {
            app.getGroupHelper()
               .createGroup(new GroupData(
                       "test1",
                       null,
                       null));
        }
    }

    @Test
    public void testGroupDelition() {

        page.groupPage()
            .goToGroupPage()
            .selectGroup()
            .delitionGroup()
            .goToGroupPage();
        int after = app.getGroupHelper()
                       .getGroupCount();
        assertEquals(before - 1, after);
        // Добавить проверку на факт удаления группы
    }
}
