package ru.ls.qa.school.addressbook.tests;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import com.codeborne.selenide.Configuration;
import com.codeborne.selenide.WebDriverRunner;
import static com.codeborne.selenide.Selectors.*;
import static com.codeborne.selenide.Selenide.*;
import static org.junit.jupiter.api.Assertions.*;
import org.openqa.selenium.Dimension;
import ru.ls.qa.school.addressbook.tests.TestBase;

import java.util.*;
public class ContactDelitionTests extends TestBase {

  @Test
  void testContactDelition() {
    page.mainPage()
            .editContact()
            .deleteContact();
  }
}
