package ru.ls.qa.school.addressbook.tests;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.model.ContactCreationData;
import ru.ls.qa.school.addressbook.model.ContactModificationData;
import ru.ls.qa.school.addressbook.model.GroupData;

import static com.codeborne.selenide.Selectors.*;
import static com.codeborne.selenide.Selenide.*;

public class ContactModificationTests extends TestBase {
  @Test
  void testContactModification(){
    page.сontactModificationPage
            .editContact()
            .fillContactForm(new ContactCreationData(
                    "Alex2",
                    "Zaytsev2",
                    "Sergeevich2",
                    "Zayats",
                    "АУУ",
                    "икуиук",
                    "Лига ставок",
                    "Лесная 3",
                    "АДрес смотри",
                    "5453425",
                    "26543543",
                    "46345",
                    "htrg@bghb.ru",
                    "brb@brevb.ru",
                    "bregvb@brevb.ru",
                    "12",
                    "March",
                    "1999",
                    "12",
                    "March",
                    "1999",
                    null,
                    "Витебский",
                    "83244375",
                    "62534"))
            .submitModificationContactForm()
            .goToHomePage();
  }
}

