package ru.ls.qa.school.addressbook.tests;// Generated by Selenium IDE
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.model.ContactCreationData;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class ContactCreationTests extends TestBase {

  private static int before;
  @BeforeAll
    static void setUp() {
    before = app.getContactHelper().getContactCount();
  }

  @Test
  void testContactCreation(){

    page.mainPage()
            .initContactCreation()
            .fillContactForm(new ContactCreationData(
            "Alex",
            "Zaytsev",
            "Sergeevich",
            "Zayats",
            "АУУ"))
            .submitContactForm()
            .goToHomePage();
//            int after = app.getContactHelper().getContactCount();
//            assertEquals(before + 1, after);
  }
}

