package ru.ls.qa.school.addressbook.tests;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.model.ContactCreationData;

public class ContactCreationTests extends TestBase {

  @Test
  void testContactCreation(){

    page.mainPage()
            .initContactCreation()
            .fillContactForm(new ContactCreationData(
            "Alex",
            "Zaytsev",
            "Sergeevich",
            "Zayats",
            "АУУ",
            "икуиук",
            "Лига ставок",
            "Лесная 3",
            "АДрес смотри",
            "5453425",
            "26543543",
            "46345",
            "htrg@bghb.ru",
            "brb@brevb.ru",
            "bregvb@brevb.ru",
            "12",
            "March",
            "1999",
            "12",
            "March",
            "1999",
            "test1",
            "Витебский",
            "83244375",
            "62534"))
            .submitContactForm()
            .goToHomePage();
  }
}

