package ru.ls.qa.school.addressbook.tests;// Generated by Selenium IDE
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.model.GroupData;
import static org.assertj.core.api.Assertions.*;
import ru.ls.qa.school.addressbook.pages.GroupListPage;

public class GroupDelitionTests extends TestBase {

    @BeforeEach
    public void precondition() {
        page.groupPage()
                .goToGroupPage();
        if(! app.getGroupHelper().isThereAGroup()){
            app.getGroupHelper().createGroup(new GroupData(
                    "test1",
                    null,
                    null));
        }
    }
  @Test
  public void testGroupDelition() {

      page.groupPage()
            .goToGroupPage()
            .selectGroup()
            .delitionGroup()
            .goToGroupPage();
      // Добавить проверку на факт удаления группы
  }
}
