package ru.ls.qa.school.addressbook.tests;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.model.GroupData;

public class GroupCreationTests extends TestBase {

  @Test
  public void testGroupCreation() {


    page.mainPage()
            .goToGroupPage()
            .initGroupCreation()
            .fillGroupForm(new GroupData(
            "test1",
            "test2",
            "test3"))
            .submitGroupForm();
//    groupCreationTestsPage
//            .goToGroupPage()
//            .initGroupCreation()
//            .fillGroupForm()
//            .submitGroupForm()
//            .returnToGroupPage();
  }

}
