package ru.ls.qa.school.addressbook.tests;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.model.GroupData;
import ru.ls.qa.school.addressbook.pages.GroupCreationTestsPage;

public class GroupCreationTests extends TestBase {

  @Test
  public void testGroupCreation() {

    groupCreationTestsPage
            .goToGroupPage()
            .initGroupCreation()
            .fillGroupForm()
            .submitGroupForm()
            .returnToGroupPage();
  }

}
