package ru.ls.qa.school.addressbook.tests;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;

public class GroupDelitionTests extends TestBase {

  @Test
  public void testGroupDelition() {

    page.groupPage()
            .goToGroupPage()
            .selectGroup()
            .delitionGroup()
            .goToGroupPage();

  }
}
