package ru.ls.qa.school.addressbook.pages;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.appmanager.ApplicationManager;
import ru.ls.qa.school.addressbook.model.GroupData;
import ru.ls.qa.school.addressbook.tests.TestBase;

public class GroupDelitionTestsPage extends HeadAbsPages {

  public GroupDelitionTestsPage(ApplicationManager app) {

    super(app);
  }

  public GroupDelitionTestsPage goToGroupPage() {
    app.getNavigationHelper().goToGroupPage();

    return this;
  }

  public GroupDelitionTestsPage returnToGroupPage() {
    app.getGroupHelper().returnToGroupPage();

    return this;
  }

  public GroupDelitionTestsPage selectGroup() {
    app.getGroupHelper().selectGroup();

    return this;
  }
  public GroupDelitionTestsPage delitionGroup() {
    app.getGroupHelper().deleteSelectedGroups();

    return this;
  }
}