package ru.ls.qa.school.addressbook.pages;// Generated by Selenium IDE
import org.checkerframework.checker.units.qual.A;
import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.appmanager.ApplicationManager;
import ru.ls.qa.school.addressbook.appmanager.GroupHelper;
import ru.ls.qa.school.addressbook.model.GroupData;
import ru.ls.qa.school.addressbook.tests.TestBase;

public class GroupCreationTestsPage extends HeadAbsPages{

    public GroupCreationTestsPage(ApplicationManager app) {

        super(app);
    }


    public GroupCreationTestsPage goToGroupPage() {
        app.getNavigationHelper().goToGroupPage();

        return this;
    }

    public GroupCreationTestsPage initGroupCreation() {
        app.getGroupHelper().initGroupCreation();

        return this;
    }

    public GroupCreationTestsPage fillGroupForm() {
        app.getGroupHelper().fillGroupForm(new GroupData("test 2", "test2", "test2"));

        return this;
    }

    public GroupCreationTestsPage submitGroupForm() {
        app.getGroupHelper().submitGroupForm();

        return this;
    }

    public GroupCreationTestsPage returnToGroupPage() {
        app.getGroupHelper().returnToGroupPage();

        return this;
    }

    public GroupCreationTestsPage selectGroup() {
        app.getGroupHelper().selectGroup();

        return this;
    }
    public GroupCreationTestsPage delitionGroup() {
        app.getGroupHelper().deleteSelectedGroups();

        return this;
    }

    public GroupCreationTestsPage logout() {
        app.getSessionHelper().logout();

        return this;
    }


}
