package ru.ls.qa.school.addressbook.pages;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.appmanager.ApplicationManager;
import ru.ls.qa.school.addressbook.tests.TestBase;

public class GroupDelitionTestsPage extends HeadAbsPages {

  public GroupDelitionTestsPage(ApplicationManager app) {

    super(app);
  }
}