package ru.ls.qa.school.addressbook.pages;// Generated by Selenium IDE
import ru.ls.qa.school.addressbook.model.GroupData;

import static ru.ls.qa.school.addressbook.tests.TestBase.app;

public class GroupCreationPage extends HeadAbsPages {

    public GroupCreationPage initGroupCreation() {
        app.group().initGroupCreation();

        return this;
    }

    public GroupCreationPage fillGroupForm(GroupData groupData) {
        app.group().fillGroupForm(groupData);

        return this;
    }

    public GroupCreationPage submitGroupForm() {
        app.group().submitGroupForm();

        return this;
    }

}
