package ru.ls.qa.school.addressbook.pages;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.tests.TestBase;

public class GroupDelitionTestsPage extends TestBase {

  @Test
  public void testGroupDelition() {
    app.getNavigationHelper().goToGroupPage();
    app.getGroupHelper().selectGroup();
    app.getGroupHelper().deleteSelectedGroups();
    app.getGroupHelper().returnToGroupPage();
  }

}
