package ru.ls.qa.school.addressbook.tests.contacts;// Generated by Selenium IDE

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.model.ContactData;
import ru.ls.qa.school.addressbook.model.GroupData;
import ru.ls.qa.school.addressbook.tests.TestBase;

import static org.assertj.core.api.Assertions.assertThat;

public class ContactDelitionTests extends TestBase {

    private static int before;
    @BeforeAll
    static void setUp() {
        before = app.getContactHelper()
                .getContactCount();
    }

    @BeforeEach
    public void precondition2() {
        if (!app.getContactHelper()
                .isThereAContact()) {
            page.mainPage()
                .initContactCreation();
            app.getContactHelper()
               .createContact(new ContactData(
                       "Alex",
                       "Zaytsev",
                       "Sergeevich",
                       "Zayats",
                       "АУУ"));

        }
    }

    @Test
    void testContactDelition() {
        page.mainPage()
            .editContact()
            .deleteContact()
            .goToHomePage();


        int after = app.getContactHelper()
                        .getContactCount();

        assertThat(after)
                .as("Сравниваем количество контактов ДО и ПОСЛЕ удаления")
                .isEqualTo(before - 1);
    }
}
