package ru.ls.qa.school.addressbook.tests.contacts;// Generated by Selenium IDE

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.model.ContactData;
import ru.ls.qa.school.addressbook.model.GroupData;
import ru.ls.qa.school.addressbook.tests.TestBase;

public class ContactModificationTests extends TestBase {

    @BeforeEach
    public void precondition1() {
        page.groupPage()
            .goToGroupPage();
        if (!app.getGroupHelper()
                .isThereAGroup()) {
            app.getGroupHelper()
               .createGroup(new GroupData(
                       "test1",
                       null,
                       null));
        }
    }

    @BeforeEach
    public void precondition2() {
        page.mainPage()
            .initContactCreation();
        if (!app.getContactHelper()
                .isThereAContact()) {
            app.getContactHelper()
               .createContact(new ContactData(
                       "Alex",
                       "Zaytsev",
                       "Sergeevich",
                       "Zayats",
                       "АУУ"));
        }
    }

    @Test
    void testContactModification() {
        page.сontactModificationPage
                .editContact()
                .fillContactForm(new ContactData(
                        "Alex2",
                        "Zaytsev2",
                        "Sergeevich2",
                        "Zayats",
                        "АУУ"))
                .submitModificationContactForm()
                .goToHomePage();
    }
}

