package ru.ls.qa.school.addressbook;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;

public class GroupCreationTests extends TestBase {

  @Test
  public void testGroupCreation() {
    goTogroupPage();
    initGroupCreation();
    fillGroupForm(new GroupData("test1", "test2", "test3"));
    submitGroupForm();
    goTogroupPage();
    Logout();
  }

}
